name: ai-detector
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python==3.10
  - pip==24.0
  - pytorch::pytorch=2.2.2=*cuda12.1*
  - numpy=1.26
  - transformers==4.41.2
  - datasets==2.19.1
  - accelerate==0.30.1
  - scikit-learn==1.4.2
  - pyyaml==6.0.1
  - tqdm==4.66.4
  - pillow==10.3.0
  - pytest==8.4.2
  - pytest-mock==3.15.1
  - pip:
    - dvc==3.66.1
    - dvc-s3==3.2.2
    - boto3==1.41.5
    - torchvision==0.17.2
    - mlflow==3.8.1